//
//  DailyQuoteService.swift
//  InkSlate
//

import SwiftUI
import Combine

// MARK: - Daily Quote Service
class DailyQuoteService: ObservableObject {
    @Published var currentQuote: DailyQuote?
    @Published var isLoading = false
    
    private let userDefaults = UserDefaults.standard
    private let cloudStore = NSUbiquitousKeyValueStore.default
    private let lastQuoteDateKey = "lastQuoteDate"
    private let currentQuoteIdKey = "currentQuoteId"
    
    // Your comprehensive collection of 600 quotes
    private let quotes = [
        DailyQuote(text: "You only live once, but if you do it right, once is enough.", author: "Mae West", category: "Life"),
        DailyQuote(text: "Dream as if you'll live forever. Live as if you'll die today.", author: "James Dean", category: "Life"),
        DailyQuote(text: "I got loyalty, got royalty inside my DNA.", author: "Kendrick Lamar", category: "Music"),
        DailyQuote(text: "Don't count the days. Make the days count.", author: "Muhammad Ali", category: "Motivation"),
        DailyQuote(text: "The road goes on forever and the party never ends.", author: "Robert Earl Keen", category: "Music"),
        DailyQuote(text: "I'm gonna love you forever, forever and ever, amen.", author: "Randy Travis", category: "Love"),
        DailyQuote(text: "Hard times create strong men.", author: "G. Michael Hopf", category: "Strength"),
        DailyQuote(text: "A man who stands for nothing will fall for anything.", author: "Malcolm X", category: "Character"),
        DailyQuote(text: "Hustle until your haters ask if you're hiring.", author: "Anonymous", category: "Success"),
        DailyQuote(text: "Love is when the soul starts to sing and the flowers of your life bloom on their own.", author: "Rabindranath Tagore", category: "Love"),
        DailyQuote(text: "You can't handle the truth!", author: "Colonel Jessup, A Few Good Men", category: "Truth"),
        DailyQuote(text: "Every saint has a past, and every sinner has a future.", author: "Oscar Wilde", category: "Redemption"),
        DailyQuote(text: "Stay far from timid. Only make moves when your heart's in it.", author: "The Notorious B.I.G.", category: "Courage"),
        DailyQuote(text: "If you want the rainbow, you gotta put up with the rain.", author: "Dolly Parton", category: "Perseverance"),
        DailyQuote(text: "Faithless is he that says farewell when the road darkens.", author: "J.R.R. Tolkien", category: "Faith"),
        DailyQuote(text: "Success is my only option, failure's not.", author: "Eminem", category: "Success"),
        DailyQuote(text: "I wish there was a way to know you're in the good old days before you've actually left them.", author: "Andy Bernard", category: "Nostalgia"),
        DailyQuote(text: "If you can't outplay them, outwork them.", author: "Ben Hogan", category: "Work Ethic"),
        DailyQuote(text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt", category: "Action"),
        DailyQuote(text: "When you love what you have, you have everything you need.", author: "Anonymous", category: "Contentment"),
        DailyQuote(text: "Be humble. Sit down.", author: "Kendrick Lamar", category: "Humility"),
        DailyQuote(text: "She believed she could, so she did.", author: "R.S. Grey", category: "Belief"),
        DailyQuote(text: "I am the one who knocks.", author: "Walter White", category: "Power"),
        DailyQuote(text: "There's a difference between knowing the path and walking the path.", author: "Morpheus", category: "Wisdom"),
        DailyQuote(text: "Real eyes realize real lies.", author: "Tupac Shakur", category: "Truth"),
        DailyQuote(text: "Cowards die many times before their deaths.", author: "William Shakespeare", category: "Courage"),
        DailyQuote(text: "Live like you were dying.", author: "Tim McGraw", category: "Life"),
        DailyQuote(text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt", category: "Dreams"),
        DailyQuote(text: "Legends never die.", author: "League of Legends", category: "Legacy"),
        DailyQuote(text: "Family don't end with blood.", author: "Bobby Singer, Supernatural", category: "Family"),
        DailyQuote(text: "You can't pour from an empty cup.", author: "Anonymous", category: "Self-Care"),
        DailyQuote(text: "Ain't nothin' to it but to do it.", author: "Ronnie Coleman", category: "Action"),
        DailyQuote(text: "No rain, no flowers.", author: "Anonymous", category: "Growth"),
        DailyQuote(text: "Money can't buy happiness, but it can buy whiskey, and that's close enough.", author: "Chris Stapleton", category: "Humor"),
        DailyQuote(text: "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward.", author: "Rocky Balboa", category: "Resilience"),
        DailyQuote(text: "When you have eliminated the impossible, whatever remains must be the truth.", author: "Sherlock Holmes", category: "Logic"),
        DailyQuote(text: "If you want to fly, give up everything that weighs you down.", author: "Buddha", category: "Freedom"),
        DailyQuote(text: "Winners focus on winning. Losers focus on winners.", author: "Anonymous", category: "Focus"),
        DailyQuote(text: "It was always you.", author: "The Notebook", category: "Love"),
        DailyQuote(text: "Pressure makes diamonds.", author: "George S. Patton", category: "Pressure"),
        DailyQuote(text: "Die with memories, not dreams.", author: "Anonymous", category: "Life"),
        DailyQuote(text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius", category: "Persistence"),
        DailyQuote(text: "I love you more than coffee, but please don't make me prove it.", author: "Anonymous", category: "Humor"),
        DailyQuote(text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela", category: "Resilience"),
        DailyQuote(text: "Take your broken heart, make it into art.", author: "Carrie Fisher", category: "Healing"),
        DailyQuote(text: "I'm a lover, not a fighter, but I'll fight for what I love.", author: "Unknown", category: "Love"),
        DailyQuote(text: "Work hard in silence, let your success make the noise.", author: "Frank Ocean", category: "Success"),
        DailyQuote(text: "The moment you stop chasing the wrong things, the right ones catch you.", author: "Lolly Daskal", category: "Focus"),
        DailyQuote(text: "You'll have bad times, but it'll wake you up to the good ones you weren't paying attention to.", author: "Good Will Hunting", category: "Perspective"),
        DailyQuote(text: "Don't be eye candy. Be soul food.", author: "Anonymous", category: "Character"),
        DailyQuote(text: "I don't chase dreams, I hunt goals.", author: "Anonymous", category: "Goals"),
        DailyQuote(text: "The wound is the place where the Light enters you.", author: "Rumi", category: "Healing"),
        DailyQuote(text: "If you ain't first, you're last.", author: "Ricky Bobby", category: "Competition"),
        DailyQuote(text: "Love is friendship set on fire.", author: "Jeremy Taylor", category: "Love"),
        DailyQuote(text: "A smooth sea never made a skilled sailor.", author: "Franklin D. Roosevelt", category: "Growth"),
        DailyQuote(text: "Everything will be okay in the end. If it's not okay, it's not the end.", author: "John Lennon", category: "Hope"),
        DailyQuote(text: "I don't need easy. I just need possible.", author: "Bethany Hamilton", category: "Determination"),
        DailyQuote(text: "All we have to decide is what to do with the time that is given us.", author: "Gandalf", category: "Time"),
        DailyQuote(text: "Fall seven times, stand up eight.", author: "Japanese Proverb", category: "Resilience"),
        DailyQuote(text: "I ain't here to be average, I'm here to be awesome.", author: "Anonymous", category: "Excellence"),
        DailyQuote(text: "Ain't nothing like the sound of freedom.", author: "Jason Aldean", category: "Freedom"),
        DailyQuote(text: "Don't trade respect for attention.", author: "Anonymous", category: "Character"),
        DailyQuote(text: "If you want something you've never had, you must be willing to do something you've never done.", author: "Thomas Jefferson", category: "Change"),
        DailyQuote(text: "My mama didn't raise no quitter.", author: "Luke Combs", category: "Persistence"),
        DailyQuote(text: "You get what you give.", author: "New Radicals", category: "Karma"),
        DailyQuote(text: "The only way out is through.", author: "Robert Frost", category: "Perseverance"),
        DailyQuote(text: "I'm still standing.", author: "Elton John", category: "Resilience"),
        DailyQuote(text: "Time you enjoy wasting was not wasted.", author: "John Lennon", category: "Time"),
        DailyQuote(text: "Be so good they can't ignore you.", author: "Steve Martin", category: "Excellence"),
        DailyQuote(text: "Don't wish for it. Work for it.", author: "Anonymous", category: "Work"),
        DailyQuote(text: "You can't stop the waves, but you can learn to surf.", author: "Jon Kabat-Zinn", category: "Adaptation"),
        DailyQuote(text: "The harder you work, the luckier you get.", author: "Gary Player", category: "Success"),
        DailyQuote(text: "Love hard when there is love to be had.", author: "Maya Angelou", category: "Love"),
        DailyQuote(text: "I'd rather be hated for who I am than loved for who I'm not.", author: "Kurt Cobain", category: "Authenticity"),
        DailyQuote(text: "You don't drown by falling in water; you drown by staying there.", author: "Ed Cole", category: "Action"),
        DailyQuote(text: "Keep your head up.", author: "Tupac Shakur", category: "Hope"),
        DailyQuote(text: "Every scar tells a story.", author: "Anonymous", category: "Healing"),
        DailyQuote(text: "If you can dream it, you can do it.", author: "Walt Disney", category: "Dreams"),
        DailyQuote(text: "Happiness is only real when shared.", author: "Christopher McCandless", category: "Happiness"),
        DailyQuote(text: "I love you more than yesterday, but less than tomorrow.", author: "Anonymous", category: "Love"),
        DailyQuote(text: "The comeback is always stronger than the setback.", author: "Anonymous", category: "Resilience"),
        DailyQuote(text: "God gives his toughest battles to his strongest soldiers.", author: "Anonymous", category: "Faith"),
        DailyQuote(text: "Chase dreams, not people.", author: "Anonymous", category: "Focus"),
        DailyQuote(text: "You're only as young as the last time you changed your mind.", author: "Timothy Leary", category: "Growth"),
        DailyQuote(text: "It's a beautiful day to save lives.", author: "Dr. Derek Shepherd", category: "Purpose"),
        DailyQuote(text: "Better an oops than a what if.", author: "Anonymous", category: "Courage"),
        DailyQuote(text: "I ain't afraid to love hard. That's the only way I know.", author: "Morgan Wallen", category: "Love"),
        DailyQuote(text: "You can't build a reputation on what you're going to do.", author: "Henry Ford", category: "Action"),
        DailyQuote(text: "Silence is a source of great strength.", author: "Lao Tzu", category: "Wisdom"),
        DailyQuote(text: "At first they'll ask why you're doing it. Later they'll ask how you did it.", author: "Anonymous", category: "Success"),
        DailyQuote(text: "Love is the only force capable of transforming an enemy into a friend.", author: "Martin Luther King Jr.", category: "Love"),
        DailyQuote(text: "You can't buy class.", author: "Lady Gaga", category: "Character"),
        DailyQuote(text: "Victory loves preparation.", author: "Anonymous", category: "Preparation"),
        DailyQuote(text: "If you want to change the world, start by making your bed.", author: "Admiral William H. McRaven", category: "Discipline"),
        DailyQuote(text: "You have enemies? Good. That means you stood up for something.", author: "Winston Churchill", category: "Courage"),
        DailyQuote(text: "I'm in love with the struggle.", author: "Nipsey Hussle", category: "Persistence"),
        DailyQuote(text: "You make me want to be a better man.", author: "As Good As It Gets", category: "Love"),
        DailyQuote(text: "Kindness is gangster.", author: "Anonymous", category: "Kindness"),
        DailyQuote(text: "Cowboy up.", author: "Western Saying", category: "Courage"),
        DailyQuote(text: "Legends are born from pain, not comfort.", author: "Anonymous", category: "Growth"),
        DailyQuote(text: "When you give up, your dreams and everything else they represent are gone.", author: "Ichigo Kurosaki, Bleach", category: "Dreams"),
        DailyQuote(text: "Sometimes life's too uncertain to have regrets.", author: "Goku, Dragon Ball Z", category: "Life"),
        DailyQuote(text: "The world isn't perfect. But it's there for us, trying the best it can... that's what makes it so damn beautiful.", author: "Roy Mustang, Fullmetal Alchemist", category: "Beauty"),
        DailyQuote(text: "You can't sit around envying other people's worlds. You have to go out and change your own.", author: "Shinichi Chiaki, Nodame Cantabile", category: "Action"),
        DailyQuote(text: "It's not the face that makes someone a monster; it's the choices they make with their lives.", author: "Naruto Uzumaki", category: "Character"),
        DailyQuote(text: "A lesson without pain is meaningless.", author: "Edward Elric, Fullmetal Alchemist", category: "Growth"),
        DailyQuote(text: "When you have something to protect, that's when you become truly strong.", author: "Naruto Uzumaki", category: "Strength"),
        DailyQuote(text: "You either die a hero or live long enough to see yourself become the villain.", author: "Harvey Dent, The Dark Knight", category: "Character"),
        DailyQuote(text: "Why do we fall, Bruce? So we can learn to pick ourselves up.", author: "Thomas Wayne, Batman Begins", category: "Resilience"),
        DailyQuote(text: "The night is darkest just before the dawn.", author: "Harvey Dent", category: "Hope"),
        DailyQuote(text: "You can't change what's been done, but you can choose what happens next.", author: "Tony Stark", category: "Choice"),
        DailyQuote(text: "Whatever happens, happens.", author: "Spike Spiegel, Cowboy Bebop", category: "Acceptance"),
        DailyQuote(text: "The past can hurt. But the way I see it, you can either run from it or learn from it.", author: "Rafiki, The Lion King", category: "Growth"),
        DailyQuote(text: "Not all treasure is silver and gold, mate.", author: "Jack Sparrow", category: "Values"),
        DailyQuote(text: "It's what you do right now that makes a difference.", author: "Black Panther, Captain America: Civil War", category: "Action"),
        DailyQuote(text: "Love is putting someone else's needs before yours.", author: "Olaf, Frozen", category: "Love"),
        DailyQuote(text: "When you decide to be something, you can be it.", author: "Frank Costello, The Departed", category: "Belief"),
        DailyQuote(text: "Sometimes you gotta run before you can walk.", author: "Tony Stark", category: "Courage"),
        DailyQuote(text: "Even miracles take a little time.", author: "Fairy Godmother, Cinderella", category: "Patience"),
        DailyQuote(text: "Our lives are defined by opportunities, even the ones we miss.", author: "Benjamin Button", category: "Opportunity"),
        DailyQuote(text: "A dream that you dream alone is only a dream. A dream you dream together is reality.", author: "John Lennon", category: "Dreams"),
        DailyQuote(text: "Life moves pretty fast. If you don't stop and look around once in a while, you could miss it.", author: "Ferris Bueller", category: "Life"),
        DailyQuote(text: "No one can make you feel inferior without your consent.", author: "Eleanor Roosevelt", category: "Self-Worth"),
        DailyQuote(text: "It's not our abilities that show who we truly are, it's our choices.", author: "Dumbledore", category: "Character"),
        DailyQuote(text: "Some people are worth melting for.", author: "Olaf", category: "Love"),
        DailyQuote(text: "We all make choices, but in the end, our choices make us.", author: "Andrew Ryan, BioShock", category: "Choice"),
        DailyQuote(text: "Get busy living, or get busy dying.", author: "Andy Dufresne", category: "Life"),
        DailyQuote(text: "You mustn't be afraid to dream a little bigger, darling.", author: "Eames, Inception", category: "Dreams"),
        DailyQuote(text: "Love means never having to say you're sorry.", author: "Love Story", category: "Love"),
        DailyQuote(text: "You can't save everyone, Peter.", author: "Aunt May, Spider-Man", category: "Limits"),
        DailyQuote(text: "A man who doesn't spend time with his family can never be a real man.", author: "Vito Corleone", category: "Family"),
        DailyQuote(text: "It's not the years, honey. It's the mileage.", author: "Indiana Jones", category: "Experience"),
        DailyQuote(text: "Sometimes you need to destroy something beautiful to know what you had.", author: "Tyler Durden", category: "Loss"),
        DailyQuote(text: "The needs of the many outweigh the needs of the few.", author: "Spock", category: "Sacrifice"),
        DailyQuote(text: "You can't be half a gangster.", author: "Jimmy Conway, Goodfellas", category: "Commitment"),
        DailyQuote(text: "Happiness can be found even in the darkest of times, if one only remembers to turn on the light.", author: "Dumbledore", category: "Hope"),
        DailyQuote(text: "Hope is a good thing, maybe the best of things.", author: "Andy Dufresne", category: "Hope"),
        DailyQuote(text: "A true hero isn't measured by the size of his strength, but by the strength of his heart.", author: "Zeus, Hercules", category: "Character"),
        DailyQuote(text: "It's not who I am underneath, but what I do that defines me.", author: "Batman", category: "Action"),
        DailyQuote(text: "Life is not the amount of breaths you take, it's the moments that take your breath away.", author: "Hitch", category: "Life"),
        DailyQuote(text: "You either build or destroy — that's life.", author: "Tupac Shakur", category: "Life"),
        DailyQuote(text: "Power is not given to you. You have to take it.", author: "Beyoncé", category: "Power"),
        DailyQuote(text: "If you want peace, prepare for war.", author: "Vegeta", category: "Preparation"),
        DailyQuote(text: "You can't cross the sea merely by standing and staring at the water.", author: "Rabindranath Tagore", category: "Action"),
        DailyQuote(text: "When you look at someone through rose-colored glasses, all the red flags just look like flags.", author: "Wanda, BoJack Horseman", category: "Love"),
        DailyQuote(text: "The world is yours.", author: "Tony Montana", category: "Success"),
        DailyQuote(text: "If you win, you live. If you lose, you die. If you don't fight, you can't win.", author: "Eren Yeager", category: "Fighting"),
        DailyQuote(text: "In this world, there are things you can't back down on.", author: "Kenshin Himura", category: "Principles"),
        DailyQuote(text: "A lesson learned the hard way is the lesson that sticks.", author: "Roronoa Zoro", category: "Learning"),
        DailyQuote(text: "The weak are destined to lie beneath the boots of the strong.", author: "Aizen Sosuke", category: "Power"),
        DailyQuote(text: "You don't have to be fearless. Just don't let fear stop you.", author: "The Princess Diaries", category: "Courage"),
        DailyQuote(text: "You can't change the world without getting your hands dirty.", author: "Lelouch vi Britannia", category: "Action"),
        DailyQuote(text: "If you don't take risks, you can't create a future.", author: "Monkey D. Luffy", category: "Risk"),
        DailyQuote(text: "When something is important enough, you do it even if the odds aren't in your favor.", author: "Elon Musk", category: "Determination"),
        DailyQuote(text: "The world will ask you who you are, and if you don't know, the world will tell you.", author: "Carl Jung", category: "Identity"),
        DailyQuote(text: "Courage is being scared to death but saddling up anyway.", author: "John Wayne", category: "Courage"),
        DailyQuote(text: "I'm gonna make him an offer he can't refuse.", author: "Vito Corleone", category: "Power"),
        DailyQuote(text: "The problem is not the problem. The problem is your attitude about the problem.", author: "Jack Sparrow", category: "Perspective"),
        DailyQuote(text: "Sometimes to find peace, you must first make war.", author: "Kratos", category: "Conflict"),
        DailyQuote(text: "It's not much of a tail, but I'm sort of attached to it.", author: "Eeyore", category: "Humor"),
        DailyQuote(text: "You don't need a reason to help people.", author: "Zidane Tribal, Final Fantasy IX", category: "Kindness"),
        DailyQuote(text: "The world is cruel, but it's also very beautiful.", author: "Mikasa Ackerman", category: "Beauty"),
        DailyQuote(text: "The circumstances of one's birth are irrelevant; it is what you do with the gift of life that determines who you are.", author: "Mewtwo", category: "Character"),
        DailyQuote(text: "Life is not fair, but it's still good.", author: "Anonymous", category: "Life"),
        DailyQuote(text: "You either die a hero, or live long enough to see yourself become a meme.", author: "Internet Wisdom", category: "Humor"),
        DailyQuote(text: "A true king's power is his compassion.", author: "Mufasa", category: "Leadership"),
        DailyQuote(text: "I am the danger.", author: "Walter White", category: "Power"),
        DailyQuote(text: "We're all stories, in the end. Just make it a good one.", author: "The Doctor", category: "Life"),
        DailyQuote(text: "Don't ever let someone tell you you can't do something.", author: "Chris Gardner, The Pursuit of Happyness", category: "Belief"),
        DailyQuote(text: "Without commitment, you'll never start. Without consistency, you'll never finish.", author: "Denzel Washington", category: "Persistence"),
        DailyQuote(text: "Don't cry because it's over, smile because it happened.", author: "Dr. Seuss", category: "Gratitude"),
        DailyQuote(text: "Sometimes you gotta be your own hero.", author: "Anonymous", category: "Self-Reliance"),
        DailyQuote(text: "The best revenge is massive success.", author: "Frank Sinatra", category: "Success"),
        DailyQuote(text: "It ain't about how hard life hits you, it's about how hard you can get hit and keep moving forward.", author: "Rocky Balboa", category: "Resilience"),
        DailyQuote(text: "You never know how strong you are until being strong is your only choice.", author: "Bob Marley", category: "Strength"),
        DailyQuote(text: "Every man's got a breaking point.", author: "Sergeant Barnes, Platoon", category: "Limits"),
        DailyQuote(text: "The things you own end up owning you.", author: "Tyler Durden", category: "Materialism"),
        DailyQuote(text: "You cannot kill what you did not create.", author: "Avenged Sevenfold", category: "Existence"),
        DailyQuote(text: "There's bravery in being soft.", author: "Anonymous", category: "Vulnerability"),
        DailyQuote(text: "When you change the way you look at things, the things you look at change.", author: "Wayne Dyer", category: "Perspective"),
        DailyQuote(text: "A man who fears suffering is already suffering from what he fears.", author: "Michel de Montaigne", category: "Fear"),
        DailyQuote(text: "Your future is whatever you make it.", author: "Doc Brown, Back to the Future", category: "Future"),
        DailyQuote(text: "All men die, not all men really live.", author: "William Wallace", category: "Life"),
        DailyQuote(text: "You must unlearn what you have learned.", author: "Yoda", category: "Learning"),
        DailyQuote(text: "There's no place like home.", author: "Dorothy Gale", category: "Home"),
        DailyQuote(text: "Sometimes it's the very people who no one imagines anything of who do the things no one can imagine.", author: "Alan Turing", category: "Potential"),
        DailyQuote(text: "You have to let it all go, Neo. Fear, doubt, disbelief.", author: "Morpheus", category: "Faith"),
        DailyQuote(text: "If you're good at something, never do it for free.", author: "Joker", category: "Value"),
        DailyQuote(text: "The greatest teacher, failure is.", author: "Yoda", category: "Learning"),
        DailyQuote(text: "In the end, we only regret the chances we didn't take.", author: "Lewis Carroll", category: "Regret"),
        DailyQuote(text: "Life's a climb, but the view is great.", author: "Hannah Montana: The Movie", category: "Life"),
        DailyQuote(text: "The man who has no imagination has no wings.", author: "Muhammad Ali", category: "Imagination"),
        DailyQuote(text: "If you can't fly, then run. If you can't run, then walk. But whatever you do, keep moving forward.", author: "Martin Luther King Jr.", category: "Persistence"),
        DailyQuote(text: "When we hit our lowest point, we are open to the greatest change.", author: "Aang, Avatar: The Last Airbender", category: "Change"),
        DailyQuote(text: "The people who are crazy enough to think they can change the world are the ones who do.", author: "Steve Jobs", category: "Innovation"),
        DailyQuote(text: "Life is tough, my darling, but so are you.", author: "Stephanie Bennett Henry", category: "Strength"),
        DailyQuote(text: "Nothing is impossible. The word itself says 'I'm possible.'", author: "Audrey Hepburn", category: "Possibility"),
        DailyQuote(text: "The goal isn't to live forever. The goal is to create something that will.", author: "Chuck Palahniuk", category: "Legacy"),
        DailyQuote(text: "Your move, chief.", author: "Sean Maguire, Good Will Hunting", category: "Choice"),
        DailyQuote(text: "The world doesn't owe you anything, kid.", author: "Clint Eastwood", category: "Reality"),
        DailyQuote(text: "A lesson in chasing dreams: if you don't run, you'll never get there.", author: "Anonymous", category: "Dreams"),
        DailyQuote(text: "Power comes in response to a need, not a desire.", author: "Goku", category: "Power"),
        DailyQuote(text: "When you give up, that's when the game is over.", author: "Misaki Ayuzawa", category: "Persistence"),
        DailyQuote(text: "All we have to decide is what to do with the time that is given us.", author: "Gandalf", category: "Time"),
        DailyQuote(text: "There's no place for a lone wolf in a pack.", author: "Shanks, One Piece", category: "Community"),
        DailyQuote(text: "The only limits that exist are the ones in your own mind.", author: "Anonymous", category: "Limits"),
        DailyQuote(text: "To be number one, you have to be odd.", author: "Dr. Seuss", category: "Uniqueness"),
        DailyQuote(text: "People die when they are killed.", author: "Shirō Emiya", category: "Logic"),
        DailyQuote(text: "Don't wish it were easier; wish you were better.", author: "Jim Rohn", category: "Growth"),
        DailyQuote(text: "Love is the only force strong enough to turn an enemy into a friend.", author: "Martin Luther King Jr.", category: "Love"),
        DailyQuote(text: "Even if it's a little, you have to keep moving forward.", author: "Connie Springer", category: "Progress"),
        DailyQuote(text: "Life is short; smile while you still have teeth.", author: "Mallory Hopkins", category: "Humor"),
        DailyQuote(text: "I'm not great at advice. Can I interest you in a sarcastic comment?", author: "Chandler Bing", category: "Humor"),
        DailyQuote(text: "Every man must decide whether he will walk in the light of creative altruism or in the darkness of destructive selfishness.", author: "Martin Luther King Jr.", category: "Choice"),
        DailyQuote(text: "Love doesn't need to be perfect; it just needs to be honest.", author: "Anonymous", category: "Love"),
        DailyQuote(text: "When you stand for nothing, you'll fall for anything.", author: "Alexander Hamilton", category: "Principles"),
        DailyQuote(text: "You can't live your life for other people.", author: "Nicholas Sparks", category: "Authenticity"),
        DailyQuote(text: "A lesson without pain is meaningless.", author: "Edward Elric", category: "Learning"),
        DailyQuote(text: "Fear cuts deeper than swords.", author: "Arya Stark", category: "Fear"),
        DailyQuote(text: "If you don't fight for what you want, don't cry for what you lose.", author: "Naruto Uzumaki", category: "Action"),
        DailyQuote(text: "Sometimes you have to take a leap of faith first. The trust part comes later.", author: "Batman", category: "Faith"),
        DailyQuote(text: "A man who has friends must himself be friendly.", author: "Proverbs 18:24", category: "Friendship"),
        DailyQuote(text: "Happiness is a warm gun.", author: "The Beatles", category: "Happiness"),
        DailyQuote(text: "No one saves us but ourselves.", author: "Buddha", category: "Self-Reliance"),
        DailyQuote(text: "A dream is not reality, but who's to say which is which?", author: "Alice Kingsleigh", category: "Reality"),
        DailyQuote(text: "Never let success get to your head, and never let failure get to your heart.", author: "Drake", category: "Balance"),
        DailyQuote(text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde", category: "Authenticity"),
        DailyQuote(text: "One good thing about music, when it hits you, you feel no pain.", author: "Bob Marley", category: "Music"),
        DailyQuote(text: "When you're a kid, they tell you it's all grow up and get a job. But the truth is, the world is yours.", author: "Scarface", category: "Potential"),
        DailyQuote(text: "Sometimes you have to lose something precious to gain something priceless.", author: "Anonymous", category: "Sacrifice"),
        DailyQuote(text: "If you can't convince them, confuse them.", author: "Harry S. Truman", category: "Strategy"),
        DailyQuote(text: "If you don't risk anything, you risk even more.", author: "Erica Jong", category: "Risk"),
        DailyQuote(text: "A man's character is his fate.", author: "Heraclitus", category: "Character"),
        DailyQuote(text: "A lesson in love: don't chase, attract.", author: "Anonymous", category: "Love"),
        DailyQuote(text: "To infinity and beyond!", author: "Buzz Lightyear", category: "Dreams"),
        DailyQuote(text: "The measure of a man is what he does with power.", author: "Plato", category: "Power"),
        DailyQuote(text: "The truth is out there.", author: "Fox Mulder", category: "Truth"),
        DailyQuote(text: "I can do this all day.", author: "Steve Rogers", category: "Persistence"),
        DailyQuote(text: "There's a difference between living and just existing.", author: "Anonymous", category: "Life"),
        DailyQuote(text: "A king's time as ruler rises and falls like the sun.", author: "Mufasa", category: "Leadership"),
        DailyQuote(text: "Don't let the noise of others' opinions drown out your inner voice.", author: "Steve Jobs", category: "Authenticity"),
        DailyQuote(text: "The world's not perfect, but it's trying.", author: "Roy Mustang", category: "Hope"),
        DailyQuote(text: "It is our choices that show what we truly are.", author: "Albus Dumbledore", category: "Choice"),
        DailyQuote(text: "We all float down here.", author: "Pennywise", category: "Horror"),
        DailyQuote(text: "Pain is weakness leaving the body.", author: "US Marines", category: "Strength"),
        DailyQuote(text: "Wisdom is learning what to overlook.", author: "William James", category: "Wisdom"),
        DailyQuote(text: "It's not whether you get knocked down, it's whether you get up.", author: "Vince Lombardi", category: "Resilience"),
        DailyQuote(text: "People's dreams... never end.", author: "Marshall D. Teach", category: "Dreams"),
        DailyQuote(text: "You don't win friends with salad.", author: "Homer Simpson", category: "Humor"),
        DailyQuote(text: "Sometimes, you must hurt to know, fall to grow, lose to gain.", author: "Anonymous", category: "Growth"),
        DailyQuote(text: "A goal without a plan is just a wish.", author: "Antoine de Saint-Exupéry", category: "Planning"),
        DailyQuote(text: "I am vengeance. I am the night. I am Batman.", author: "Batman", category: "Identity"),
        DailyQuote(text: "You never really learn much from hearing yourself talk.", author: "George Clooney", category: "Learning"),
        DailyQuote(text: "If you want to find the secrets of the universe, think in terms of energy, frequency, and vibration.", author: "Nikola Tesla", category: "Science"),
        DailyQuote(text: "All we have is now.", author: "Anonymous", category: "Present"),
        DailyQuote(text: "The world is full of kings and queens who blind your eyes and steal your dreams.", author: "Black Sabbath", category: "Power"),
        DailyQuote(text: "The future depends on what we do in the present.", author: "Mahatma Gandhi", category: "Future"),
        DailyQuote(text: "There is beauty in simplicity.", author: "Anonymous", category: "Beauty"),
        DailyQuote(text: "When you forgive, you heal. When you let go, you grow.", author: "Anonymous", category: "Healing"),
        DailyQuote(text: "Life's not about waiting for the storm to pass, it's about learning to dance in the rain.", author: "Vivian Greene", category: "Resilience"),
        DailyQuote(text: "It's not denial. I'm just selective about the reality I accept.", author: "Garfield", category: "Reality"),
        DailyQuote(text: "Heroes get remembered, but legends never die.", author: "The Sandlot", category: "Legacy"),
        DailyQuote(text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson", category: "Destiny"),
        DailyQuote(text: "Sometimes you climb the mountain not to conquer it, but to admire the view.", author: "Anonymous", category: "Journey"),
        DailyQuote(text: "Being alone is not the same as being lonely.", author: "Anonymous", category: "Solitude"),
        DailyQuote(text: "You can't control how other people receive your energy.", author: "Anonymous", category: "Energy"),
        DailyQuote(text: "It's not strength to never fall, it's strength to get up every time you do.", author: "Guts, Berserk", category: "Strength"),
        DailyQuote(text: "War is where the young and stupid are tricked by the old and bitter.", author: "Niko Bellic", category: "War"),
        DailyQuote(text: "I am the storm.", author: "Anonymous", category: "Power"),
        DailyQuote(text: "The secret of getting ahead is getting started.", author: "Mark Twain", category: "Action"),
        DailyQuote(text: "When the going gets tough, the tough get going.", author: "Billy Ocean", category: "Resilience"),
        DailyQuote(text: "I have nothing to prove to you.", author: "Carol Danvers", category: "Confidence"),
        DailyQuote(text: "The world ain't all sunshine and rainbows.", author: "Rocky Balboa", category: "Reality"),
        DailyQuote(text: "Ain't no mountain high enough.", author: "Marvin Gaye", category: "Determination"),
        DailyQuote(text: "The only thing stronger than fear is hope.", author: "President Snow", category: "Hope"),
        DailyQuote(text: "A calm sea never made a good sailor.", author: "Anonymous", category: "Growth"),
        DailyQuote(text: "You'll never walk alone.", author: "Liverpool FC Anthem", category: "Support"),
        DailyQuote(text: "Fear is freedom! Subjugation is liberation!", author: "Satsuki Kiryuuin", category: "Freedom"),
        DailyQuote(text: "It's not over until I win.", author: "Les Brown", category: "Persistence"),
        DailyQuote(text: "You can't change fate, but you can challenge it.", author: "Naruto", category: "Fate"),
        DailyQuote(text: "Do not pity the dead, Harry. Pity the living.", author: "Dumbledore", category: "Life"),
        DailyQuote(text: "We all start as strangers.", author: "The Chainsmokers", category: "Connection"),
        DailyQuote(text: "My past does not define me.", author: "Anonymous", category: "Identity"),
        DailyQuote(text: "I'm still learning.", author: "Michelangelo", category: "Learning"),
        DailyQuote(text: "Keep moving forward.", author: "Walt Disney", category: "Progress"),
        DailyQuote(text: "Let the past die. Kill it if you have to.", author: "Kylo Ren", category: "Past"),
        DailyQuote(text: "Faith is taking the first step even when you don't see the whole staircase.", author: "Martin Luther King Jr.", category: "Faith"),
        DailyQuote(text: "The higher you climb, the colder it gets.", author: "Anonymous", category: "Success"),
        DailyQuote(text: "In war, victory. In peace, vigilance. In death, sacrifice.", author: "Halo 3", category: "War"),
        DailyQuote(text: "Whatever happens, don't lose hope.", author: "Anonymous", category: "Hope"),
        DailyQuote(text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi", category: "Change"),
        DailyQuote(text: "There's no shame in falling down. True shame is to not stand up again.", author: "Shintarō Midorima", category: "Resilience"),
        DailyQuote(text: "A single act of kindness can cause ripples in all directions.", author: "Anonymous", category: "Kindness"),
        DailyQuote(text: "You can't appreciate the light without the darkness.", author: "Anonymous", category: "Balance"),
        DailyQuote(text: "I am Iron Man.", author: "Tony Stark", category: "Identity"),
        DailyQuote(text: "We're not tools of the government, or anyone else.", author: "Solid Snake", category: "Freedom"),
        DailyQuote(text: "To protect something, I must be willing to destroy it.", author: "Light Yagami", category: "Sacrifice"),
        DailyQuote(text: "A man's worth is no greater than his ambitions.", author: "Marcus Aurelius", category: "Ambition"),
        DailyQuote(text: "I'm not afraid of dying; I'm afraid of not trying.", author: "Jay-Z", category: "Courage"),
        DailyQuote(text: "Every legend begins with a story worth telling.", author: "Anonymous", category: "Legacy"),
        DailyQuote(text: "A lesson in stillness: even the moon moves only when it must.", author: "Anonymous", category: "Patience"),
        DailyQuote(text: "You either own your story or it owns you.", author: "Brené Brown", category: "Story"),
        DailyQuote(text: "Those who forgive too easily are rarely understood.", author: "Hachiman Hikigaya, Oregairu", category: "Forgiveness"),
        DailyQuote(text: "I'd rather be hated for the truth than loved for a lie.", author: "Kenshin Himura", category: "Truth"),
        DailyQuote(text: "You become what you pretend to be.", author: "Kurt Vonnegut", category: "Identity"),
        DailyQuote(text: "People don't change; they reveal who they are under pressure.", author: "Harvey Specter", category: "Character"),
        DailyQuote(text: "When you bury pain, it teaches you nothing.", author: "Joel Miller, The Last of Us", category: "Healing"),
        DailyQuote(text: "A lesson in power: silence frightens louder men.", author: "Anonymous", category: "Power"),
        DailyQuote(text: "Even if we forget the faces of our friends, we will never forget the bonds.", author: "Angel Beats!", category: "Friendship"),
        DailyQuote(text: "The hardest wars are the ones you fight alone.", author: "Anonymous", category: "Struggle"),
        DailyQuote(text: "If you stare into the abyss long enough, it starts quoting you back.", author: "Friedrich Nietzsche", category: "Darkness"),
        DailyQuote(text: "To love someone is to learn the song in their heart and sing it when they forget.", author: "Arne Garborg", category: "Love"),
        DailyQuote(text: "Peace was never an option.", author: "Magneto", category: "Conflict"),
        DailyQuote(text: "Every legend was once a fool who tried.", author: "Anonymous", category: "Courage"),
        DailyQuote(text: "You can't kill time without injuring eternity.", author: "Henry David Thoreau", category: "Time"),
        DailyQuote(text: "The opposite of love isn't hate, it's indifference.", author: "Elie Wiesel", category: "Love"),
        DailyQuote(text: "A lesson from loss: nothing is wasted if it changes you.", author: "Anonymous", category: "Growth"),
        DailyQuote(text: "I wanted to be great, but I forgot to be kind.", author: "Anonymous", category: "Kindness"),
        DailyQuote(text: "You see what you have power to look at.", author: "Aldous Huxley", category: "Perception"),
        DailyQuote(text: "The scars you hide grow teeth.", author: "Anonymous", category: "Healing"),
        DailyQuote(text: "You don't need a happy ending to make a story worth telling.", author: "Anonymous", category: "Story"),
        DailyQuote(text: "When you win, say nothing. When you lose, say less.", author: "Paul Brown", category: "Humility"),
        DailyQuote(text: "All the gods were lonely once.", author: "American Gods", category: "Loneliness"),
        DailyQuote(text: "Every saint was a sinner with a good memory.", author: "Anonymous", category: "Redemption"),
        DailyQuote(text: "Love is not finding someone to live with; it's finding someone you can't live without.", author: "Rafael Ortiz", category: "Love"),
        DailyQuote(text: "The only difference between a hero and a madman is who tells the story.", author: "Anonymous", category: "Perspective"),
        DailyQuote(text: "Pain reminds you you're still here. Hope reminds you why.", author: "Anonymous", category: "Purpose"),
        DailyQuote(text: "In this world, isn't everything fragile?", author: "C.C., Code Geass", category: "Fragility"),
        DailyQuote(text: "You can't save people who don't want to be saved.", author: "John Constantine", category: "Limits"),
        DailyQuote(text: "Some truths are kinder when whispered.", author: "Anonymous", category: "Truth"),
        DailyQuote(text: "Even angels are monsters in someone's story.", author: "Anonymous", category: "Perspective"),
        DailyQuote(text: "The greatest prison people live in is the fear of what others think.", author: "David Icke", category: "Fear"),
        DailyQuote(text: "If you're not confused, you're not paying attention.", author: "Tom Peters", category: "Learning"),
        DailyQuote(text: "A sword is only as moral as the hand that holds it.", author: "Erwin Smith", category: "Morality"),
        DailyQuote(text: "There's a crack in everything; that's how the light gets in.", author: "Leonard Cohen", category: "Hope"),
        DailyQuote(text: "Some people build walls not to keep others out, but to see who cares enough to break them down.", author: "Anonymous", category: "Love"),
        DailyQuote(text: "Even a broken compass can point to freedom once.", author: "Anonymous", category: "Hope"),
        DailyQuote(text: "I don't believe in fate, but I do believe in consequences.", author: "Anonymous", category: "Choice"),
        DailyQuote(text: "He who conquers himself is the mightiest warrior.", author: "Confucius", category: "Self-Mastery"),
        DailyQuote(text: "You drown not by falling into a river, but by staying submerged.", author: "Paulo Coelho", category: "Action"),
        DailyQuote(text: "A man who doesn't look back at his past cannot move forward.", author: "Jet Black, Cowboy Bebop", category: "Growth"),
        DailyQuote(text: "You can't eat beauty; it doesn't feed you.", author: "Lupita Nyong'o", category: "Reality"),
        DailyQuote(text: "Love is the one game where both players can win.", author: "Anonymous", category: "Love"),
        DailyQuote(text: "We're all ghosts of the choices we didn't make.", author: "Anonymous", category: "Regret"),
        DailyQuote(text: "A flower does not think of competing with the one next to it. It just blooms.", author: "Zen Proverb", category: "Growth"),
        DailyQuote(text: "Sometimes you need to lose your mind to find your soul.", author: "Anonymous", category: "Discovery"),
        DailyQuote(text: "A little rebellion now and then is a good thing.", author: "Thomas Jefferson", category: "Rebellion"),
        DailyQuote(text: "Hearts aren't loyal to logic.", author: "Anonymous", category: "Love"),
        DailyQuote(text: "Even rain eventually runs out of sky.", author: "Anonymous", category: "Hope"),
        DailyQuote(text: "The measure of love is to love without measure.", author: "Saint Augustine", category: "Love"),
        DailyQuote(text: "Don't fear failure; fear being in the same place next year.", author: "Anonymous", category: "Growth"),
        DailyQuote(text: "I'd rather be whole than good.", author: "Carl Jung", category: "Wholeness"),
        DailyQuote(text: "You can't wake a person who is pretending to sleep.", author: "Navajo Proverb", category: "Awareness"),
        DailyQuote(text: "Love is a form of bravery.", author: "Anonymous", category: "Courage"),
        DailyQuote(text: "I don't need perfect. I need real.", author: "Anonymous", category: "Authenticity"),
        DailyQuote(text: "In a world of copies, be an original sin.", author: "Anonymous", category: "Uniqueness"),
        DailyQuote(text: "Monsters are real, and ghosts are too. They live inside us.", author: "Stephen King", category: "Darkness"),
        DailyQuote(text: "Everything that drowns me makes me want to fly.", author: "OneRepublic", category: "Resilience"),
        DailyQuote(text: "Sometimes the right path is the one you make yourself.", author: "Katara, Avatar", category: "Path"),
        DailyQuote(text: "If you want to test a man's character, give him power.", author: "Abraham Lincoln", category: "Character"),
        DailyQuote(text: "You either learn to control your emotions or they control you.", author: "Anonymous", category: "Emotions"),
        DailyQuote(text: "If you tremble with indignation at injustice, you are my comrade.", author: "Che Guevara", category: "Justice"),
        DailyQuote(text: "Faith is not the absence of doubt; it's the choice to act in spite of it.", author: "Anonymous", category: "Faith"),
        DailyQuote(text: "When everything seems to be against you, remember airplanes take off against the wind.", author: "Henry Ford", category: "Resilience"),
        DailyQuote(text: "Even if I die, my words will live.", author: "Pain, Naruto Shippuden", category: "Legacy"),
        DailyQuote(text: "You never know how much you believe something until it's truth or death.", author: "C.S. Lewis", category: "Belief"),
        DailyQuote(text: "A lion doesn't lose sleep over the opinions of sheep.", author: "Anonymous", category: "Confidence"),
        DailyQuote(text: "Some souls recognize each other by the light they carry.", author: "Anonymous", category: "Connection"),
        DailyQuote(text: "A lesson in love: timing is cruel and destiny is late.", author: "Anonymous", category: "Love"),
        DailyQuote(text: "When something you love becomes a memory, that memory becomes a treasure.", author: "Anonymous", category: "Memory"),
        DailyQuote(text: "You can't spell 'hero' without 'her.'", author: "Anonymous", category: "Equality"),
        DailyQuote(text: "The world breaks everyone, and afterward, some are strong at the broken places.", author: "Ernest Hemingway", category: "Strength"),
        DailyQuote(text: "You don't get to choose if you get hurt, but you do get to choose who hurts you.", author: "John Green", category: "Choice"),
        DailyQuote(text: "I became the person I needed as a kid.", author: "Anonymous", category: "Growth"),
        DailyQuote(text: "A man with nothing left to lose is unstoppable.", author: "Anonymous", category: "Power"),
        DailyQuote(text: "We are all stories in the making.", author: "Anonymous", category: "Story"),
        DailyQuote(text: "Kindness is not weakness. It's discipline.", author: "Anonymous", category: "Kindness"),
        DailyQuote(text: "It's better to be hated for what you are than loved for what you're not.", author: "André Gide", category: "Authenticity"),
        DailyQuote(text: "True strength is knowing when to walk away.", author: "Anonymous", category: "Wisdom"),
        DailyQuote(text: "The loneliest people are the kindest.", author: "Robin Williams", category: "Kindness"),
        DailyQuote(text: "Reality is wrong. Dreams are for real.", author: "Tupac Shakur", category: "Dreams"),
        DailyQuote(text: "Some scars never fade because they're supposed to remind you.", author: "Anonymous", category: "Memory"),
        DailyQuote(text: "If you're brave enough to say goodbye, life will reward you with a new hello.", author: "Paulo Coelho", category: "Change"),
        DailyQuote(text: "Hearts can't be repaired; they just learn to beat differently.", author: "Anonymous", category: "Healing"),
        DailyQuote(text: "Even broken crayons still color.", author: "Anonymous", category: "Value"),
        DailyQuote(text: "To love deeply is to risk deeply.", author: "Anonymous", category: "Love"),
        DailyQuote(text: "The mirror is a terrible teacher.", author: "Anonymous", category: "Self-Image"),
        DailyQuote(text: "Not all those who wander are lost.", author: "J.R.R. Tolkien", category: "Journey"),
        DailyQuote(text: "People will forget what you said, but they'll never forget how you made them feel.", author: "Maya Angelou", category: "Impact"),
        DailyQuote(text: "A villain is just a hero whose story you stopped hearing.", author: "Anonymous", category: "Perspective"),
        DailyQuote(text: "The soul always knows what to do to heal itself.", author: "Caroline Myss", category: "Healing"),
        DailyQuote(text: "You have to be a little lost to find something worth finding.", author: "Anonymous", category: "Discovery"),
        DailyQuote(text: "No light shines brighter than the one that burns after darkness.", author: "Anonymous", category: "Hope"),
        DailyQuote(text: "The truth doesn't mind being questioned; lies do.", author: "Anonymous", category: "Truth"),
        DailyQuote(text: "If you're scared, that means you still have something worth protecting.", author: "Anonymous", category: "Fear"),
        DailyQuote(text: "Sometimes the only way out is through the fire.", author: "Anonymous", category: "Courage"),
        DailyQuote(text: "Every goodbye teaches you how to love better.", author: "Anonymous", category: "Love"),
        DailyQuote(text: "Courage is fear that has said its prayers.", author: "Anonymous", category: "Courage"),
        DailyQuote(text: "Don't fall in love with potential.", author: "Anonymous", category: "Love"),
        DailyQuote(text: "The world rewards the bold, not the perfect.", author: "Anonymous", category: "Courage"),
        DailyQuote(text: "Real Gs move in silence like lasagna.", author: "Lil Wayne", category: "Success"),
        DailyQuote(text: "I'm not perfect, but I'm worth it.", author: "Lil Wayne", category: "Self-Worth"),
        DailyQuote(text: "Love me or hate me, I still shine.", author: "Lil Wayne", category: "Confidence"),
        DailyQuote(text: "The only thing on my mind is success.", author: "Lil Wayne", category: "Success"),
        DailyQuote(text: "They can knock me down, but they can't knock my hustle.", author: "Lil Wayne", category: "Persistence"),
        DailyQuote(text: "I'm too focused to lose.", author: "Lil Wayne", category: "Focus"),
        DailyQuote(text: "I grind like I'm broke, even when I'm paid.", author: "Lil Wayne", category: "Work Ethic"),
        DailyQuote(text: "Don't count the scars; count the lessons.", author: "Lil Wayne", category: "Growth"),
        DailyQuote(text: "Silence teaches louder than words.", author: "Lil Wayne", category: "Wisdom"),
        DailyQuote(text: "I turned my wounds into wisdom.", author: "Lil Wayne", category: "Healing"),
        DailyQuote(text: "The top gets lonely, but the view's still beautiful.", author: "Lil Wayne", category: "Success"),
        DailyQuote(text: "I learned to love the struggle — it built my crown.", author: "Lil Wayne", category: "Persistence"),
        DailyQuote(text: "Confidence is my cologne.", author: "Lil Wayne", category: "Confidence"),
        DailyQuote(text: "You can't spell hustle without U.", author: "Lil Wayne", category: "Work Ethic"),
        DailyQuote(text: "They doubted me so loud I had to succeed quietly.", author: "Lil Wayne", category: "Success"),
        DailyQuote(text: "I don't chase dreams; I collect them.", author: "Lil Wayne", category: "Dreams"),
        DailyQuote(text: "It's not about where you start; it's about how much fire you keep.", author: "Lil Wayne", category: "Persistence"),
        DailyQuote(text: "My pain writes better poetry than my peace ever could.", author: "Lil Wayne", category: "Art"),
        DailyQuote(text: "The mirror is my rival.", author: "Lil Wayne", category: "Self-Improvement"),
        DailyQuote(text: "Don't wait for the stars to align — rearrange them.", author: "Lil Wayne", category: "Action"),
        DailyQuote(text: "Sometimes success just sounds like breathing when you shouldn't be.", author: "Lil Wayne", category: "Success"),
        DailyQuote(text: "Every setback just recharged my battery.", author: "Lil Wayne", category: "Resilience"),
        DailyQuote(text: "Even angels envy my faith.", author: "Lil Wayne", category: "Faith"),
        DailyQuote(text: "I built my kingdom with broken bricks.", author: "Lil Wayne", category: "Success"),
        DailyQuote(text: "Dream so big they call it delusion.", author: "Lil Wayne", category: "Dreams"),
        DailyQuote(text: "No weapon formed against me gets Wi-Fi.", author: "Lil Wayne", category: "Protection"),
        DailyQuote(text: "Hustle until your critics start quoting you.", author: "Lil Wayne", category: "Success"),
        DailyQuote(text: "A king ain't crowned — he's carved.", author: "Lil Wayne", category: "Leadership"),
        DailyQuote(text: "If you can't be the best, be unforgettable.", author: "Lil Wayne", category: "Excellence"),
        DailyQuote(text: "Don't pray for lighter burdens; pray for stronger shoulders.", author: "Lil Wayne", category: "Strength"),
        DailyQuote(text: "I didn't find myself — I created myself.", author: "Lil Wayne", category: "Identity"),
        DailyQuote(text: "Pressure made diamonds, but pain made legends.", author: "Lil Wayne", category: "Growth"),
        DailyQuote(text: "Success is my silence talking.", author: "Lil Wayne", category: "Success"),
        DailyQuote(text: "If it doesn't scare you, it won't change you.", author: "Lil Wayne", category: "Growth"),
        DailyQuote(text: "I don't need a throne to know I'm royalty.", author: "Lil Wayne", category: "Self-Worth"),
        DailyQuote(text: "Scars are proof that I survived my own storm.", author: "Lil Wayne", category: "Resilience"),
        DailyQuote(text: "They watched me fall and called it proof — I called it training.", author: "Lil Wayne", category: "Growth"),
        DailyQuote(text: "My only competition is yesterday's me.", author: "Lil Wayne", category: "Self-Improvement"),
        DailyQuote(text: "When you learn to dance in chaos, peace becomes a weapon.", author: "Lil Wayne", category: "Adaptation"),
        DailyQuote(text: "Ain't no ceiling for a man who built his own sky.", author: "Lil Wayne", category: "Potential"),
        DailyQuote(text: "I don't rap about pain — I translate it.", author: "Lil Wayne", category: "Art"),
        DailyQuote(text: "My success wasn't luck — it was late nights and faith.", author: "Lil Wayne", category: "Success"),
        DailyQuote(text: "The grind don't sleep — it dreams in motion.", author: "Lil Wayne", category: "Work Ethic"),
        DailyQuote(text: "I'm allergic to average.", author: "Lil Wayne", category: "Excellence"),
        DailyQuote(text: "I was born ready, just needed a moment.", author: "Lil Wayne", category: "Preparation"),
        DailyQuote(text: "Real power moves quietly — just like God does.", author: "Lil Wayne", category: "Power"),
        DailyQuote(text: "I'm the product of prayer and pressure.", author: "Lil Wayne", category: "Faith"),
        DailyQuote(text: "Keep your head high and your faith higher.", author: "Lil Wayne", category: "Faith"),
        DailyQuote(text: "I've been to hell and came back with souvenirs.", author: "Lil Wayne", category: "Resilience"),
        DailyQuote(text: "If you want to fly, you gotta burn your excuses.", author: "Lil Wayne", category: "Action"),
        DailyQuote(text: "Do or do not. There is no try.", author: "Yoda", category: "Action"),
        DailyQuote(text: "Your focus determines your reality.", author: "Qui-Gon Jinn", category: "Focus"),
        DailyQuote(text: "The Force will be with you. Always.", author: "Obi-Wan Kenobi", category: "Faith"),
        DailyQuote(text: "I find your lack of faith disturbing.", author: "Darth Vader", category: "Faith"),
        DailyQuote(text: "In my experience, there is no such thing as luck.", author: "Obi-Wan Kenobi", category: "Preparation"),
        DailyQuote(text: "The greatest teacher, failure is.", author: "Yoda", category: "Learning"),
        DailyQuote(text: "Never tell me the odds.", author: "Han Solo", category: "Courage"),
        DailyQuote(text: "Hope is like the sun. If you only believe in it when you see it, you'll never make it through the night.", author: "Leia Organa", category: "Hope"),
        DailyQuote(text: "Rebellions are built on hope.", author: "Jyn Erso", category: "Hope"),
        DailyQuote(text: "Stay on target.", author: "Gold Five", category: "Focus"),
        DailyQuote(text: "Fear is the path to the dark side.", author: "Yoda", category: "Fear"),
        DailyQuote(text: "You can't stop the change, any more than you can stop the suns from setting.", author: "Shmi Skywalker", category: "Change"),
        DailyQuote(text: "The Force is strong with this one.", author: "Darth Vader", category: "Power"),
        DailyQuote(text: "The ability to destroy a planet is insignificant next to the power of the Force.", author: "Darth Vader", category: "Power"),
        DailyQuote(text: "Strike me down, and I will become more powerful than you can possibly imagine.", author: "Obi-Wan Kenobi", category: "Sacrifice"),
        DailyQuote(text: "It is our choices that show what we truly are, far more than our abilities.", author: "Dumbledore", category: "Character"),
        DailyQuote(text: "Happiness can be found even in the darkest of times, if one only remembers to turn on the light.", author: "Dumbledore", category: "Hope"),
        DailyQuote(text: "Working hard is important, but there's something that matters even more: believing in yourself.", author: "Harry Potter", category: "Belief"),
        DailyQuote(text: "It matters not what someone is born, but what they grow to be.", author: "Dumbledore", category: "Growth"),
        DailyQuote(text: "The ones that love us never really leave us.", author: "Sirius Black", category: "Love"),
        DailyQuote(text: "You're a little scary sometimes, you know that? Brilliant... but scary.", author: "Ron Weasley", category: "Intelligence"),
        DailyQuote(text: "We've all got both light and dark inside us. What matters is the part we choose to act on.", author: "Sirius Black", category: "Choice"),
        DailyQuote(text: "It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.", author: "Dumbledore", category: "Courage"),
        DailyQuote(text: "The truth. It is a beautiful and terrible thing, and should therefore be treated with great caution.", author: "Dumbledore", category: "Truth"),
        DailyQuote(text: "Fear of a name increases fear of the thing itself.", author: "Hermione Granger", category: "Fear"),
        DailyQuote(text: "All we have to decide is what to do with the time that is given us.", author: "Gandalf", category: "Time"),
        DailyQuote(text: "Even the smallest person can change the course of the future.", author: "Galadriel", category: "Potential"),
        DailyQuote(text: "I would rather share one lifetime with you than face all the ages of this world alone.", author: "Arwen", category: "Love"),
        DailyQuote(text: "Not all those who wander are lost.", author: "J.R.R. Tolkien", category: "Journey"),
        DailyQuote(text: "There is some good in this world, and it's worth fighting for.", author: "Samwise Gamgee", category: "Hope"),
        DailyQuote(text: "A day may come when the courage of men fails… but it is not this day.", author: "Aragorn", category: "Courage"),
        DailyQuote(text: "You shall not pass!", author: "Gandalf", category: "Courage"),
        DailyQuote(text: "It's a dangerous business, going out your door.", author: "Bilbo Baggins", category: "Adventure"),
        DailyQuote(text: "Deeds will not be less valiant because they are unpraised.", author: "Aragorn", category: "Character"),
        DailyQuote(text: "Even darkness must pass. A new day will come.", author: "Samwise Gamgee", category: "Hope"),
        DailyQuote(text: "Be water, my friend.", author: "Bruce Lee", category: "Adaptation"),
        DailyQuote(text: "You have power over your mind, not outside events.", author: "Marcus Aurelius", category: "Control"),
        DailyQuote(text: "It always seems impossible until it's done.", author: "Nelson Mandela", category: "Possibility"),
        DailyQuote(text: "The future depends on what you do today.", author: "Mahatma Gandhi", category: "Action"),
        DailyQuote(text: "Adapt what is useful, reject what is useless, and add what is specifically your own.", author: "Bruce Lee", category: "Growth"),
        DailyQuote(text: "We must all face the choice between what is right and what is easy.", author: "Dumbledore", category: "Choice"),
        DailyQuote(text: "If you want peace, prepare for war.", author: "Vegeta", category: "Preparation"),
        DailyQuote(text: "Fear is the mind-killer.", author: "Frank Herbert", category: "Fear"),
        DailyQuote(text: "Don't tell me the sky's the limit when there are footprints on the moon.", author: "Paul Brandt", category: "Potential"),
        DailyQuote(text: "Victory is reserved for those willing to pay its price.", author: "Sun Tzu", category: "Success"),
        DailyQuote(text: "Dreams don't work unless you do.", author: "John C. Maxwell", category: "Work"),
        DailyQuote(text: "A single dream is more powerful than a thousand realities.", author: "J.R.R. Tolkien", category: "Dreams"),
        DailyQuote(text: "May the Force be with you.", author: "Star Wars", category: "Faith"),
        DailyQuote(text: "Legends never die.", author: "League of Legends", category: "Legacy"),
        DailyQuote(text: "Faith and grind — that's the empire recipe.", author: "Lil Wayne", category: "Success"),
        DailyQuote(text: "You either die a hero, or you live long enough to see yourself become the villain.", author: "Harvey Dent", category: "Character"),
        DailyQuote(text: "The fear of loss is a path to the dark side.", author: "Yoda", category: "Fear"),
        DailyQuote(text: "Power is not evil. What's evil is the mind that wields it.", author: "Code Geass", category: "Power"),
        DailyQuote(text: "I did what I had to do.", author: "Walter White", category: "Choice"),
        DailyQuote(text: "I am the danger.", author: "Walter White", category: "Power"),
        DailyQuote(text: "Redemption is just another word for starting over.", author: "Anonymous", category: "Redemption"),
        DailyQuote(text: "What is grief, if not love persevering?", author: "Vision", category: "Love"),
        DailyQuote(text: "Sometimes you must burn bridges to keep the light.", author: "Anonymous", category: "Sacrifice"),
        DailyQuote(text: "I have nothing left but my enemies.", author: "Darth Maul", category: "Isolation"),
        DailyQuote(text: "I became what they made me.", author: "Anakin Skywalker", category: "Identity"),
        DailyQuote(text: "A man who justifies everything can justify anything.", author: "Anonymous", category: "Morality"),
        DailyQuote(text: "The hardest prison to escape is your past.", author: "Anonymous", category: "Past"),
        DailyQuote(text: "There is no peace without a war inside.", author: "Anonymous", category: "Conflict"),
        DailyQuote(text: "You must lose everything to gain yourself.", author: "Tyler Durden", category: "Identity"),
        DailyQuote(text: "Scars are medals branded on flesh.", author: "Zuko", category: "Healing"),
        DailyQuote(text: "I've done terrible things, but not without reason.", author: "Magneto", category: "Justification"),
        DailyQuote(text: "Every saint has a shadow.", author: "Anonymous", category: "Humanity"),
        DailyQuote(text: "I never wanted to be a hero. I just didn't want to be forgotten.", author: "Anonymous", category: "Legacy"),
        DailyQuote(text: "We're all monsters to someone.", author: "The Witcher", category: "Perspective"),
        DailyQuote(text: "The chains of the past are broken only by fire.", author: "Daenerys Targaryen", category: "Freedom"),
        DailyQuote(text: "Fear doesn't shut you down. It wakes you up.", author: "Four, Divergent", category: "Fear"),
        DailyQuote(text: "They laugh at the scars they can't see.", author: "Anonymous", category: "Healing"),
        DailyQuote(text: "Forgiveness is the longest road home.", author: "Anonymous", category: "Forgiveness"),
        DailyQuote(text: "The greatest trick the devil ever pulled was convincing the world he didn't exist.", author: "Verbal Kint", category: "Deception"),
        DailyQuote(text: "Sometimes you have to be the villain in someone else's story to stay the hero in your own.", author: "Anonymous", category: "Perspective"),
        DailyQuote(text: "I was never lost. I was just becoming.", author: "Anonymous", category: "Growth"),
        DailyQuote(text: "You either control the darkness or it controls you.", author: "Anonymous", category: "Control"),
        DailyQuote(text: "A hero's fall is just a villain's origin story.", author: "Anonymous", category: "Transformation"),
        DailyQuote(text: "It's not the fall that defines you. It's what you do after you hit the ground.", author: "Batman", category: "Resilience"),
        DailyQuote(text: "Pain demands to be felt.", author: "John Green", category: "Pain"),
        DailyQuote(text: "The light burns brightest in those who have walked through darkness.", author: "Anonymous", category: "Strength"),
        DailyQuote(text: "You think darkness is your ally?", author: "Bane", category: "Power"),
        DailyQuote(text: "You don't get to choose redemption; you earn it.", author: "Anonymous", category: "Redemption"),
        DailyQuote(text: "I'm not broken — I'm battle-tested.", author: "Lil Wayne", category: "Strength"),
        DailyQuote(text: "Sometimes the villain is just the hero who waited too long.", author: "Anonymous", category: "Timing"),
        DailyQuote(text: "If you stare into the abyss, the abyss stares back.", author: "Nietzsche", category: "Darkness"),
        DailyQuote(text: "I am the one who knocks.", author: "Walter White", category: "Power"),
        DailyQuote(text: "The world only remembers winners.", author: "Tywin Lannister", category: "Success"),
        DailyQuote(text: "You can't save everyone, but you can try anyway.", author: "Spider-Man", category: "Heroism"),
        DailyQuote(text: "The fire that burns twice as bright burns half as long.", author: "Lao Tzu", category: "Intensity"),
        DailyQuote(text: "I'll be the monster if that's what it takes to end the nightmare.", author: "Lelouch vi Britannia", category: "Sacrifice"),
        DailyQuote(text: "The devil whispered, 'You can't withstand the storm.' I whispered back, 'I am the storm.'", author: "Anonymous", category: "Power"),
        DailyQuote(text: "Some men just want to watch the world burn.", author: "Alfred Pennyworth", category: "Chaos"),
        DailyQuote(text: "You can't undo the past, but you can outgrow it.", author: "Anonymous", category: "Growth"),
        DailyQuote(text: "I am vengeance. I am the night.", author: "Batman", category: "Justice"),
        DailyQuote(text: "I didn't fall from grace. I dove.", author: "Lil Wayne", category: "Choice"),
        DailyQuote(text: "You'll never understand me if you've never bled for something.", author: "Anonymous", category: "Sacrifice"),
        DailyQuote(text: "There is no redemption without ruin.", author: "Anonymous", category: "Redemption"),
        DailyQuote(text: "My pain became my passport.", author: "Lil Wayne", category: "Growth"),
        DailyQuote(text: "When you've been through hell, heaven feels earned.", author: "Lil Wayne", category: "Appreciation"),
        DailyQuote(text: "The villain is just the hero who stopped pretending.", author: "Anonymous", category: "Authenticity"),
        DailyQuote(text: "You don't know freedom until you lose everything.", author: "Anonymous", category: "Freedom"),
        DailyQuote(text: "You can't break what's already broken.", author: "Lil Wayne", category: "Resilience"),
        DailyQuote(text: "Even the devil was once an angel.", author: "Anonymous", category: "Transformation"),
        DailyQuote(text: "A soul in chains still dreams of wings.", author: "Anonymous", category: "Hope"),
        DailyQuote(text: "They made me out of pieces and expected me to be whole.", author: "Anonymous", category: "Healing"),
        DailyQuote(text: "You'll be surprised what grows in darkness.", author: "Anonymous", category: "Growth"),
        DailyQuote(text: "Regret is a cruel teacher.", author: "Snape", category: "Learning"),
        DailyQuote(text: "Look at me. You have your mother's eyes.", author: "Snape", category: "Love"),
        DailyQuote(text: "Always.", author: "Snape", category: "Love"),
        DailyQuote(text: "You'll never know true strength until your heart breaks.", author: "Anonymous", category: "Strength"),
        DailyQuote(text: "Every sinner's prayer sounds like hope.", author: "Anonymous", category: "Hope"),
        DailyQuote(text: "They called it rebellion. I called it clarity.", author: "Anakin Skywalker", category: "Truth"),
        DailyQuote(text: "I became fire because I was tired of being burned.", author: "Anonymous", category: "Transformation"),
        DailyQuote(text: "You can't rise if you never fell.", author: "Anonymous", category: "Growth"),
        DailyQuote(text: "I built my empire from the ashes of who I used to be.", author: "Lil Wayne", category: "Success"),
        DailyQuote(text: "Sometimes mercy is just cruelty wearing a smile.", author: "Anonymous", category: "Deception"),
        DailyQuote(text: "To outgrow your demons, you must feed them truth.", author: "Anonymous", category: "Healing"),
        DailyQuote(text: "The world doesn't forgive soft hearts.", author: "Anonymous", category: "Reality"),
        DailyQuote(text: "My crown came from scars, not silver.", author: "Lil Wayne", category: "Success"),
        DailyQuote(text: "Villains never start as villains. They start as believers.", author: "Anonymous", category: "Transformation"),
        DailyQuote(text: "A lion doesn't apologize for roaring.", author: "Anonymous", category: "Confidence"),
        DailyQuote(text: "Every hero is one bad day away from me.", author: "The Joker", category: "Fragility"),
        DailyQuote(text: "You either build a throne from your pain or a grave.", author: "Lil Wayne", category: "Choice"),
        DailyQuote(text: "You can't destroy me; I already did that myself.", author: "Anonymous", category: "Resilience"),
        DailyQuote(text: "I didn't lose my way — I lit it on fire.", author: "Anonymous", category: "Transformation"),
        DailyQuote(text: "We all wear masks; some just fit better.", author: "The Mask", category: "Identity"),
        DailyQuote(text: "You can't save your soul by killing your fire.", author: "Anonymous", category: "Authenticity"),
        DailyQuote(text: "The closer you are to the light, the darker your shadow becomes.", author: "Kingdom Hearts", category: "Balance"),
        DailyQuote(text: "I'm not what happened to me; I'm what I chose to become.", author: "Carl Jung", category: "Choice"),
        DailyQuote(text: "If I must fall, let it be from grace.", author: "Anonymous", category: "Dignity"),
        DailyQuote(text: "Even fallen angels remember the sky.", author: "Anonymous", category: "Memory"),
        DailyQuote(text: "Redemption is rebellion against your own past.", author: "Anonymous", category: "Redemption"),
        DailyQuote(text: "I was forged in what they thought would destroy me.", author: "Lil Wayne", category: "Strength"),
        DailyQuote(text: "A hero would've quit. I adapted.", author: "Lil Wayne", category: "Adaptation"),
        DailyQuote(text: "Sometimes survival looks like sin.", author: "Anonymous", category: "Survival"),
        DailyQuote(text: "Even monsters need love to stay alive.", author: "Anonymous", category: "Love"),
        DailyQuote(text: "A villain is just a hero with no witnesses.", author: "Anonymous", category: "Perspective"),
        DailyQuote(text: "The fire didn't change me — it revealed me.", author: "Anonymous", category: "Identity"),
        DailyQuote(text: "You can't heal what you still hide.", author: "Anonymous", category: "Healing"),
        DailyQuote(text: "I don't need forgiveness. I need focus.", author: "Lil Wayne", category: "Focus"),
        DailyQuote(text: "When I was buried, I learned to breathe dirt.", author: "Anonymous", category: "Adaptation"),
        DailyQuote(text: "I may have fallen, but I fell forward.", author: "Anonymous", category: "Progress"),
        DailyQuote(text: "The past is a grave I stopped visiting.", author: "Anonymous", category: "Healing"),
        DailyQuote(text: "You can't cage what doesn't care to escape.", author: "Anonymous", category: "Freedom"),
        DailyQuote(text: "I burned my old self to light my new path.", author: "Anonymous", category: "Transformation"),
        DailyQuote(text: "Monsters aren't born; they're built in silence.", author: "Anonymous", category: "Transformation"),
        DailyQuote(text: "My faith was tested in fire and came out armor.", author: "Lil Wayne", category: "Faith"),
        DailyQuote(text: "I am both the storm and the calm after.", author: "Anonymous", category: "Balance"),
        DailyQuote(text: "Redemption isn't given — it's earned in blood, sweat, and silence.", author: "Anonymous", category: "Redemption")
    ]
    
    init() {
        setupCloudStoreObserver()
        cloudStore.synchronize()
        loadDailyQuote()
    }
    
    deinit {
        NotificationCenter.default.removeObserver(self)
    }
    
    private func setupCloudStoreObserver() {
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(cloudStoreDidChange),
            name: NSUbiquitousKeyValueStore.didChangeExternallyNotification,
            object: cloudStore
        )
    }
    
    @objc private func cloudStoreDidChange(_ notification: Notification) {
        DispatchQueue.main.async {
            self.loadDailyQuote()
        }
    }
    
    func loadDailyQuote() {
        let today = Calendar.current.startOfDay(for: Date())
        
        // Try to load from iCloud first, then fall back to local UserDefaults
        var lastQuoteDate: Date
        var quoteId: Int?
        
        // Check iCloud first
        if let cloudDate = cloudStore.object(forKey: lastQuoteDateKey) as? Date {
            lastQuoteDate = cloudDate
            quoteId = cloudStore.object(forKey: currentQuoteIdKey) as? Int
        } else if let localDate = userDefaults.object(forKey: lastQuoteDateKey) as? Date {
            // Fall back to local and migrate to iCloud
            lastQuoteDate = localDate
            quoteId = userDefaults.object(forKey: currentQuoteIdKey) as? Int
        } else {
            lastQuoteDate = Date.distantPast
        }
        
        let lastQuoteDateStart = Calendar.current.startOfDay(for: lastQuoteDate)
        
        // If it's a new day, get a new quote
        if today > lastQuoteDateStart {
            selectNewQuote()
        } else {
            // Load the current quote from storage
            if let id = quoteId, id < quotes.count {
                currentQuote = quotes[id]
            } else {
                // Fallback to first quote if no valid quote ID
                currentQuote = quotes[0]
            }
        }
    }
    
    private func selectNewQuote() {
        // Get a random quote that's different from yesterday's
        let lastQuoteId = (cloudStore.object(forKey: currentQuoteIdKey) as? Int) 
            ?? (userDefaults.object(forKey: currentQuoteIdKey) as? Int) 
            ?? -1
        var newQuoteId: Int
        
        repeat {
            newQuoteId = Int.random(in: 0..<quotes.count)
        } while newQuoteId == lastQuoteId && quotes.count > 1
        
        currentQuote = quotes[newQuoteId]
        
        // Save to both iCloud and local UserDefaults
        let now = Date()
        cloudStore.set(newQuoteId, forKey: currentQuoteIdKey)
        cloudStore.set(now, forKey: lastQuoteDateKey)
        cloudStore.synchronize()
        
        // Also save locally as backup
        userDefaults.set(newQuoteId, forKey: currentQuoteIdKey)
        userDefaults.set(now, forKey: lastQuoteDateKey)
    }
    
    func refreshQuote() {
        selectNewQuote()
    }
}

// MARK: - Daily Quote Model
struct DailyQuote: Identifiable, Codable {
    let id: UUID
    let text: String
    let author: String
    let category: String
    
    init(text: String, author: String, category: String) {
        self.id = UUID()
        self.text = text
        self.author = author
        self.category = category
    }
}