import Foundation

enum JournalPromptLibrary {
    static func randomPrompt(for kind: JournalPromptKind) -> String {
        switch kind {
        case .dailyReflection:
            return dailyReflection.randomElement() ?? "What did you learn today?"
        case .deepExistential:
            return deepExistential.randomElement() ?? "What truth are you avoiding saying out loud?"
        }
    }

    static let dailyReflection: [String] = [
        "What did you do today that felt worth doing?",
        "What did you avoid doing today and why?",
        "What moment today stuck with you and why?",
        "How did you feel when you woke up today versus now?",
        "What small thing did you do today that mattered?",
        "Who did you interact with today and what did those interactions reveal about you?",
        "What did today teach you?",
        "What did you do today that aligned with your values?",
        "Describe the quality of today in one color and explain why.",
        "What did you say today that you wish you could take back?",
        "What did today's challenges teach you about yourself?",
        "How did you treat yourself today?",
        "What did you notice about yourself today that you usually miss?",
        "What small victory happened today?",
        "How present were you today?",
        "What did you accomplish today that you're proud of?",
        "What distracted you most today?",
        "How did your body feel today?",
        "What did you consume today that nourished you?",
        "What did you consume that drained you?",
        "How kind were you to yourself today?",
        "What did today reveal about your current season of life?",
        "What are you carrying into tomorrow that you don't need to?",
        "What did you learn about your capacity today?",
        "How did you spend your energy today?",
        "What made you laugh or smile today?",
        "What frustrated you most today?",
        "How many times today did you check out emotionally?",
        "What decision did you make today that mattered?",
        "How honest were you with yourself today?",
        "What did you give today?",
        "What did you receive today?",
        "How did you move your body today?",
        "What did you think about most today?",
        "What conversation affected you today?",
        "How did you handle something difficult today?",
        "What are you grateful for from today?",
        "What do you regret from today?",
        "What surprised you about yourself today?",
        "How did today feel in your nervous system?",
        "What old patterns showed up today?",
        "How did you honor your boundaries today?",
        "What did you learn about someone else today?",
        "How did you show up for others today?",
        "What did you create or build today?",
        "What do you want to accomplish tomorrow?",
        "What are you dreading about tomorrow?",
        "What do you want to prioritize tomorrow?",
        "How would you want to spend tomorrow if you had zero obligations?",
        "What would make tomorrow better than today?",
        "What do you want to practice tomorrow?",
        "What are you planning to do differently tomorrow?",
        "What do you want to create or build tomorrow?",
        "What conversation do you want to have tomorrow?",
        "What's one thing you want to do differently tomorrow?",
        "What do you want tomorrow to feel like?",
        "What are you hoping for tomorrow?",
        "What are you worried about for tomorrow?",
        "What small goal do you want to hit tomorrow?",
        "How do you want to move tomorrow?",
        "What do you want to eat or consume tomorrow?",
        "What boundary do you want to set tomorrow?",
        "Who do you want to connect with tomorrow?",
        "What do you want to say out loud tomorrow?",
        "How do you want to spend your free time tomorrow?",
        "What habit do you want to start tomorrow?",
        "What do you want to let go of before tomorrow starts?",
        "How do you want to treat yourself tomorrow?",
        "What challenge are you ready to face tomorrow?",
        "What are you committed to tomorrow?",
        "How do you want others to feel around you tomorrow?",
        "What do you want to notice tomorrow?",
        "What are you excited about for tomorrow?",
        "What do you want to learn tomorrow?",
        "How do you want to show up tomorrow?",
        "What conversation are you preparing for tomorrow?",
        "What do you want to be more intentional about tomorrow?",
        "How will you know tomorrow was successful?",
        "What are you willing to try tomorrow?",
        "What do you want to protect tomorrow?",
        "What do you want to release before tomorrow?",
        "How do you want to feel in your body tomorrow?",
        "What risks do you want to take tomorrow?",
        "What do you want to appreciate about tomorrow?",
        "How will you practice self-compassion tomorrow?",
        "What are you choosing to focus on tomorrow?",
        "What do you want to give tomorrow?",
        "What do you want to receive tomorrow?",
        "How do you want to respond differently tomorrow?",
        "What do you want your tomorrow to be about?"
    ]

    static let deepExistential: [String] = [
        "What belief about yourself have you never questioned until now?",
        "Describe a moment when someone saw you differently than you saw yourself. How did it change you?",
        "What would you do if you knew no one would judge you?",
        "Write about a time you felt truly seen by another person.",
        "What patterns do you keep repeating even though they hurt you?",
        "If your body could speak, what would it tell you about how you've been treating it?",
        "What does home mean to you, and where is it really?",
        "Describe the gap between who you pretend to be and who you actually are.",
        "What fear have you been carrying for so long you forgot you had it?",
        "Write about someone who hurt you. Can you understand why they did it?",
        "What would you need to forgive yourself for?",
        "Describe a moment when you felt fully alive. What were you doing?",
        "What would change if you stopped seeking approval?",
        "Write a letter to your younger self. What would you tell them?",
        "What parts of yourself have you hidden away, and why?",
        "Describe your relationship with your body and how it has changed over time.",
        "What legacy do you want to leave behind?",
        "When did you stop believing you were enough?",
        "Write about a time you chose the harder path. Was it worth it?",
        "What does vulnerability actually mean to you?",
        "Describe the last time you felt lonely even though you were surrounded by people.",
        "What truth have you been avoiding saying out loud?",
        "How do your past experiences shape the way you see the world?",
        "Write about what it means to be a good person to you specifically.",
        "What would you grieve if it disappeared from your life?",
        "Describe a moment when you realized something fundamental about yourself.",
        "What parts of your childhood still live in you?",
        "If you removed one fear, how would your life be different?",
        "Write about the last time you genuinely apologized to someone.",
        "What does home feel like in your body?",
        "Describe your relationship with time and mortality.",
        "What do you need to let go of?",
        "When do you feel most like yourself?",
        "Write about a belief you were raised with that you've since rejected.",
        "What would happen if you stopped playing small?",
        "Describe the moments when you felt seen by life itself.",
        "What is the story you tell yourself about why you're not enough?",
        "Write about a person whose forgiveness you still need.",
        "What needs are you not allowing yourself to have?",
        "Describe what freedom would actually feel like for you.",
        "What truth about yourself are you still learning to accept?",
        "Write about a time you put someone else's needs before your own survival.",
        "What does it mean to take up space?",
        "Describe the relationship between your thoughts and your pain.",
        "What would you do if you had already failed?",
        "Write about someone you've outgrown and what that feels like.",
        "What are you protecting yourself from by staying small?",
        "Describe a moment when you chose yourself.",
        "What generational patterns are you trying to break?",
        "Write about what unconditional love means to you now.",
        "If your life was a story, what chapter are you in?",
        "What do you want people to know about your struggle?",
        "Describe the difference between self-care and avoiding feelings.",
        "What would it take for you to trust yourself?",
        "Write about the masks you wear and who you are underneath them.",
        "What are you ready to stop carrying?",
        "Describe a time you felt the weight of expectations that weren't yours.",
        "What do you want to be remembered for?",
        "Write about your relationship with control.",
        "What does healing actually look like in your life?",
        "Describe the parts of yourself you're learning to love.",
        "What would you say to someone living your exact struggle?",
        "Write about a moment when your defenses cracked open.",
        "What are you honoring about your past?",
        "Describe what safety means in your body and mind.",
        "What belief about love are you unlearning?",
        "Write about the dreams you've let go of and why.",
        "What do you need to hear from yourself?",
        "Describe your relationship with your own power.",
        "What would change if you stopped abandoning yourself?",
        "Write about a moment you realized you were stronger than you thought.",
        "What parts of your identity are you still defining?",
        "Describe the gap between your values and your actions.",
        "What are you becoming?",
        "Write about your relationship with failure.",
        "What would it mean to truly honor yourself?",
        "Describe the conversations you wish you'd had.",
        "What is your body trying to tell you?",
        "Write about what you're choosing every single day.",
        "What would happen if you let people see your darkness?",
        "Describe a time you felt your own resilience.",
        "What patterns in relationships keep showing up?",
        "Write about what you need to grieve to move forward.",
        "What are you learning about yourself right now?",
        "Describe your relationship with your own voice.",
        "What would freedom actually cost you?",
        "Write about what you're building inside yourself.",
        "What do you want to stop explaining?",
        "Describe the moment you realized you had a choice.",
        "What are you becoming through this pain?",
        "Write about the stories you keep telling yourself.",
        "What does it mean to belong to yourself?",
        "Describe your relationship with time running out.",
        "What have you learned about yourself by being hurt?",
        "Write about what you're protecting by staying guarded.",
        "What truth would set you free?",
        "Describe the version of yourself you're building.",
        "What would happen if you stopped waiting?",
        "Write about how you've survived what tried to break you.",
        "What do you want your life to mean?"
    ]
}

